### ISSUE TITLE
Is it possible to have tags added for Alfresco releases?

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-repository#928]
There is a branch for 5.2.6. It would be super helpful if there were tags added for releases. In particular I'm trying to understand some changes between 5.2.5 and 5.2.6. Because there is no branch (that I can find) for 5.2.5, I'm left with an odd mixture of using Github to look at 5.2.6 source and exploding jar files in a 5.2.5 deployment and attempting to infer some changes.

**Comment by binduwavell** [comment]
It looks like this commit is likely 5.2.5: https://github.com/Alfresco/alfresco-repository/commit/65b637c3b06290769b49afa1fc926ce4622cf17e ... if that is the case then it should be reasonably easy to process through the commit history and add tags.

**Comment by ancutam** [comment]
There is no actual branch in this repository for 5.2.6, I think the one that appears was created by mistake by someone looking for it (GitHub has this feature to create a new branch just by hitting enter).
The code for releases prior to 6.0 is in a different (private) git repository.
